"""
| File: thrust_curve.py
| Author: Rodrigo Gomes (rodrigofpgomes@tecnico.ulisboa.pt)
| License: BSD-3-Clause.
| Description: Batched single-propeller thrust model for the Glider.
|
| Current model:
|
|     T = k_T * Omega_p^2
|     Q = k_M * T
|
| where T is the propeller thrust magnitude and Q is the propeller aerodynamic
| torque magnitude. The equal-and-opposite reaction torque applied to the
| fuselage is returned as a full body-frame vector.
|
| The state argument is intentionally kept in update(), although it is not used
| by this first model. It will be required when the model is extended to:
|
|     J   = V_a / (n D_p)
|     T   = rho n^2 D_p^4 C_T(J)
|     Q   = rho n^2 D_p^5 C_Q(J)
|
| without changing the GliderBatch vehicle interface.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

import torch

from pegasus.simulator.logic.state_batch import StateBatch as State
from pegasus.simulator.logic.thrusters.thrust_curve import ThrustCurve


class GliderThrustCurveBatch(ThrustCurve):
    """
    Batched thrust model for one nose-mounted propeller per glider.

    The model receives the commanded propeller angular velocity Omega_p [rad/s]
    and returns:
        thrust: Shape (n_vehicles, 1), thrust magnitude [N].

        rotor_velocity: Shape (n_vehicles, 1), actual propeller angular velocity [rad/s].

        reaction_moment: Shape (n_vehicles, 3), equal-and-opposite propeller reaction
                    moment acting on the fuselage, expressed in the vehicle body frame [N m].

    Notes
    -----
    The thrust *force direction* is not applied in this class. GliderBatch uses
    ``propeller_axis_body`` and applies the resulting force directly to the
    physical rotor prim. Therefore the moment caused by the thrust-line offset
    relative to the aircraft CoM is generated by PhysX and must not be added
    here.

    The only torque returned by this model is the propeller reaction torque
    about the propeller rotation axis.
    """

    def __init__(
        self,
        config: Mapping[str, Any] | None = None,
        n_vehicles: int = 1,
        device: str = "cpu",
    ) -> None:
        """ Initialize the single-propeller batch model. """

        cfg = dict(config or {})

        if n_vehicles <= 0:
            raise ValueError("n_vehicles must be greater than zero")

        self.device = device
        self.n_vehicles = int(n_vehicles)
        self._num_rotors = 1

        # ------------------------------------------------------------------
        # Current quadratic static-thrust model
        # ------------------------------------------------------------------
        self._thrust_constant = torch.as_tensor(cfg.get("thrust_constant", 8.5e-6), dtype=torch.float32, device=self.device)
        self._moment_constant = torch.as_tensor(cfg.get("moment_constant", 0.018), dtype=torch.float32, device=self.device)
        self._reaction_moment_sign = torch.as_tensor(cfg.get("reaction_moment_sign", -1.0), dtype=torch.float32, device=self.device)

        # ------------------------------------------------------------------
        # Rotor operating limits
        # ------------------------------------------------------------------
        self.min_rotor_velocity = torch.as_tensor(cfg.get("min_rotor_velocity", 0.0), dtype=torch.float32, device=self.device)
        self.max_rotor_velocity = torch.as_tensor(cfg.get("max_rotor_velocity", 1100.0), dtype=torch.float32, device=self.device)
        self._motor_time_constant = torch.as_tensor(cfg.get("motor_time_constant", 0.0), dtype=torch.float32, device=self.device)

        # ------------------------------------------------------------------
        # Propeller axis in body frame
        # ------------------------------------------------------------------
        axis = torch.as_tensor(cfg.get("propeller_axis_body", [1.0, 0.0, 0.0]), dtype=torch.float32, device=self.device)

        axis_norm = torch.linalg.vector_norm(axis)
        if float(axis_norm) <= 1e-9:
            raise ValueError("propeller_axis_body cannot be the zero vector")

        self._propeller_axis_body = axis / axis_norm

        # ------------------------------------------------------------------
        # Values reserved for the future advance-ratio model
        # ------------------------------------------------------------------
        self._air_density = float(cfg.get("air_density", 1.2041))
        self._propeller_diameter = float(cfg.get("propeller_diameter", 0.229))

        # ------------------------------------------------------------------
        # Batched state
        # ------------------------------------------------------------------
        self._input_reference = torch.zeros((self.n_vehicles, 1), dtype=torch.float32, device=self.device)

        self._velocity = torch.zeros_like(self._input_reference)
        self._force = torch.zeros_like(self._input_reference)

        # Aerodynamic torque magnitude Q before the reaction sign is applied.
        self._propeller_torque = torch.zeros_like(self._input_reference)

        # Equal-and-opposite torque acting on the fuselage, in body frame.
        self._reaction_moment = torch.zeros((self.n_vehicles, 3), dtype=torch.float32, device=self.device)

    # ------------------------------------------------------------------
    # Vehicle integration
    # ------------------------------------------------------------------

    def initialize(self, vehicle=None) -> None:
        """
        Optional initialization hook called by GliderBatch.

        If the vehicle exposes ``_propeller_axis_body``, use exactly the same
        axis for the reaction torque as GliderBatch uses for the thrust force.
        This avoids having two independently configured propeller axes.
        """

        if vehicle is None:
            return

        axis = getattr(vehicle, "_propeller_axis_body", None)
        if axis is None:
            return

        axis = torch.as_tensor(axis, dtype=torch.float32, device=self.device).reshape(-1)

        if axis.shape != (3,):
            raise ValueError(
                "The vehicle propeller axis must contain exactly 3 components"
            )

        norm = torch.linalg.vector_norm(axis)
        if float(norm) <= 1e-9:
            raise ValueError("The vehicle propeller axis cannot be zero")

        self._propeller_axis_body = axis / norm

    # ------------------------------------------------------------------
    # Input
    # ------------------------------------------------------------------

    def set_input_reference(self, input_reference) -> None:
        """
        Set the desired propeller angular velocity Omega_p [rad/s].

        Accepted input shapes are:

            scalar
            (1,)
            (n_vehicles,)
            (1, 1)
            (n_vehicles, 1)

        A single value is broadcast to all gliders.
        """

        reference = torch.as_tensor(
            input_reference,
            dtype=torch.float32,
            device=self.device,
        )

        if reference.ndim == 0:
            reference = reference.reshape(1, 1).expand(self.n_vehicles, 1)

        elif reference.ndim == 1:
            if reference.numel() == 1:
                reference = reference.reshape(1, 1).expand(self.n_vehicles, 1)
            elif reference.numel() == self.n_vehicles:
                reference = reference.reshape(self.n_vehicles, 1)
            else:
                raise ValueError(
                    "A 1-D propeller reference must contain either one value "
                    "or n_vehicles values"
                )

        elif reference.ndim == 2:
            if reference.shape == (1, 1):
                reference = reference.expand(self.n_vehicles, 1)
            elif reference.shape != (self.n_vehicles, 1):
                raise ValueError(
                    "A batched propeller reference must have shape "
                    f"({self.n_vehicles}, 1)"
                )

        else:
            raise ValueError(
                "Propeller reference must be a scalar or a tensor with at most 2 dimensions"
            )

        self._input_reference = reference

    # ------------------------------------------------------------------
    # Propeller model
    # ------------------------------------------------------------------

    def _compute_propeller_loads(
        self,
        state: State,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Compute propeller thrust T and aerodynamic torque Q.

        Current model
        -------------
            T = k_T Omega_p^2
            Q = k_M T

        ``state`` is intentionally not used yet.

        Future replacement
        ------------------
        This is the method to replace/extend when C_T(J) and C_Q(J) are added:

            n = Omega_p / (2*pi)
            J = V_a / (n * D_p)

            T = rho * n^2 * D_p^4 * C_T(J)
            Q = rho * n^2 * D_p^5 * C_Q(J)

        The public interface of GliderBatch does not need to change.
        """

        del state  # explicitly unused in the current static model

        omega_sq = torch.square(self._velocity)

        thrust = self._thrust_constant * omega_sq
        torque = self._moment_constant * thrust

        return thrust, torque

    def update(
        self,
        state: State,
        dt: float,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Update the propeller model.

        Parameters
        ----------
        state:
            Current batched vehicle state. Not used by the present static
            quadratic model, but retained for the future C_T(J)/C_Q(J) model.

        dt:
            Physics time step [s].

        Returns
        -------
        thrust:
            Tensor of shape (n_vehicles, 1), thrust magnitude [N].

        rotor_velocity:
            Tensor of shape (n_vehicles, 1), actual propeller speed [rad/s].

        reaction_moment:
            Tensor of shape (n_vehicles, 3), equal-and-opposite reaction torque
            acting on the fuselage, expressed in the body frame [N m].
        """

        # Desired speed after actuator limits.
        target_velocity = torch.clamp(
            self._input_reference,
            min=float(self.min_rotor_velocity),
            max=float(self.max_rotor_velocity),
        )

        # --------------------------------------------------------------
        # Optional first-order motor dynamics
        #
        #   dOmega/dt = (Omega_cmd - Omega) / tau_m
        #
        # tau_m <= 0 -> instantaneous motor response.
        # --------------------------------------------------------------
        tau_m = float(self._motor_time_constant)

        if tau_m <= 0.0:
            self._velocity = target_velocity
        else:
            dt_t = torch.as_tensor(
                max(float(dt), 0.0),
                dtype=torch.float32,
                device=self.device,
            )

            alpha = 1.0 - torch.exp(
                -dt_t / max(tau_m, 1e-6)
            )

            self._velocity = (
                self._velocity
                + alpha * (target_velocity - self._velocity)
            )

            self._velocity = torch.clamp(
                self._velocity,
                min=float(self.min_rotor_velocity),
                max=float(self.max_rotor_velocity),
            )

        # --------------------------------------------------------------
        # Propeller loads
        # --------------------------------------------------------------
        self._force, self._propeller_torque = self._compute_propeller_loads(
            state
        )

        # Equal-and-opposite propeller torque acting on the fuselage.
        #
        # Q is a positive magnitude. The selected sign specifies the direction
        # of the fuselage reaction torque along the propeller axis.
        reaction_scalar = (
            self._reaction_moment_sign * self._propeller_torque
        )

        self._reaction_moment = (
            reaction_scalar
            * self._propeller_axis_body.reshape(1, 3)
        )

        return self._force, self._velocity, self._reaction_moment

    # ------------------------------------------------------------------
    # Reset
    # ------------------------------------------------------------------

    def reset(self, env_ids: torch.Tensor | Sequence[int] | None = None) -> None:
        """
        Reset propeller state for all or selected environments.
        """

        if env_ids is None:
            self._input_reference.zero_()
            self._velocity.zero_()
            self._force.zero_()
            self._propeller_torque.zero_()
            self._reaction_moment.zero_()
            return

        ids = torch.as_tensor(
            env_ids,
            dtype=torch.long,
            device=self.device,
        )

        self._input_reference[ids] = 0.0
        self._velocity[ids] = 0.0
        self._force[ids] = 0.0
        self._propeller_torque[ids] = 0.0
        self._reaction_moment[ids] = 0.0

    # ------------------------------------------------------------------
    # Public properties
    # ------------------------------------------------------------------

    @property
    def force(self) -> torch.Tensor:
        """Current propeller thrust magnitude, shape (n_vehicles, 1), in N."""
        return self._force

    @property
    def velocity(self) -> torch.Tensor:
        """Current propeller angular velocity, shape (n_vehicles, 1), in rad/s."""
        return self._velocity

    @property
    def propeller_torque(self) -> torch.Tensor:
        """
        Current propeller aerodynamic torque magnitude Q,
        shape (n_vehicles, 1), in N m.
        """
        return self._propeller_torque

    @property
    def reaction_moment(self) -> torch.Tensor:
        """
        Equal-and-opposite reaction torque acting on the fuselage,
        shape (n_vehicles, 3), in body-frame N m.
        """
        return self._reaction_moment

    @property
    def rolling_moment(self) -> torch.Tensor:
        """
        Compatibility alias for existing Pegasus thrust-curve terminology.
        """
        return self._reaction_moment

    @property
    def propeller_axis_body(self) -> torch.Tensor:
        """Normalized propeller axis expressed in the body frame."""
        return self._propeller_axis_body

    @property
    def thrust_constant(self) -> torch.Tensor:
        """k_T used in T = k_T Omega^2."""
        return self._thrust_constant

    @property
    def moment_constant(self) -> torch.Tensor:
        """k_M used in Q = k_M T."""
        return self._moment_constant

    @property
    def air_density(self) -> float:
        """Air density reserved for the future C_T(J)/C_Q(J) model."""
        return self._air_density

    @property
    def propeller_diameter(self) -> float:
        """Propeller diameter reserved for the future C_T(J)/C_Q(J) model."""
        return self._propeller_diameter
